# See https://github.com/iiasa/Condor_run_R/blob/master/configuring.md
LABEL = "occupy_all_{Sys.Date()}"
JOBS = c(0:499)
HOST_REGEXP = "^limpopo"
REQUEST_MEMORY = 1000
REQUEST_DISK = 1
LAUNCHER = "Rscript"
SCRIPT = "test.R"
ARGUMENTS = "%1"
WAIT_FOR_RUN_COMPLETION = FALSE
