# See https://github.com/iiasa/Condor_run_R/blob/master/configuring.md
LABEL = "seeding_inspite_of_occupation_{Sys.Date()}"
JOBS = c(0:19)
HOST_REGEXP = "^limpopo6"
REQUEST_MEMORY = 1000
LAUNCHER = "Rscript"
SCRIPT = "test.R"
ARGUMENTS = "%1"
WAIT_FOR_RUN_COMPLETION = TRUE
