# MiB of memory to reserve
request_memory = 0

# KiB of disk on the Scratch (D:) 2TB very fast solid state drive to
# reserve for storing transient data.
# Note that the Projects (E:) 7.7TB less fast solid state drive is
# available for longer-term (but not backed up) project-related storage.
request_disk = 0

# Number of hardware threads to reserve
request_cpus = 1

executable    = job.bat
universe      = vanilla
# Schedule the job that holds on to the requested resources on a
# specific machine (execution point), and not in the seeding slot.
requirements  = TARGET.Machine == "limpopo6.iiasa.ac.at" && Seeding == FALSE
output        = reserve.out
stream_output = True
error         = reserve.err
stream_error  = True
log           = reserve.log
should_transfer_files = YES
transfer_input_files  = job.bat
notification = Never
queue
